# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Label' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'TinyConstraints'
  pod "ZSWTappableLabel", "~> 3.3"
  pod 'SnapKit'
  pod 'ZSWTaggedString', '~> 4.0'
  pod 'ZSWTaggedString/Swift', '~> 4.0'
  # Pods for Label

end
